feat: add url input modal
Kyutech-C3/ToyBox_front_replace pull request #136
Opened 2023-12-23 05:28 UTC by siloneco

## issue番号

なし

## 変更点概要

投稿ページのURL入力欄を作成しました

## 参考文献(あれば)

なし

## スクリーンショット(必要であれば)

![image](https://github.com/Kyutech-C3/ToyBox_front_replace/assets/37594486/17d466ea-5b2b-4dea-8ee8-8a8d977d498b)

## チェック項目

- [X] テストが通ったか
- [X] ビルドが通ったか
- [X] `self assign`したか
- [X] レビュー優先度のラベルをつけたか

2023-12-24 08:46 UTC, tosaken1116 requested changes

2023-12-24 08:46 UTC, tosaken1116 commented on src/components/model/Work/components/URLInput/hooks/index.ts
> +const isValidUrl = (url: string): boolean =>
![review:should](https://img.shields.io/badge/review-suggest-orange.svg) 
reactから切り離した純関数なのでlogic配下に逃したら丸いかも
できればこれに関しては単体テストが欲しいです

2023-12-24 08:46 UTC, tosaken1116 commented on src/components/model/Work/components/URLInput/hooks/index.ts
> +    useState<boolean>(false);
```suggestion
type WarningStatus = "ok"|"invalidUrl"|"duplicateUrl"
type WarningMessage =warningMessage[keyof warningMessage]
type Warning = {
status:WarningStatus
message:WarningMessage
}
const warningMessage= {
"ok":"",
"invalidUrl":"url is invalid",
"duplicateUrl": "url is already exist"
} as const 
  const [warning, setWarning] = useState<Warning>({status:"ok",message:""});
```

ってやると状態持つ変数が一つで済むからいいかも？
(型は記憶で書いたので間違ってたらすみません)

2023-12-24 08:46 UTC, tosaken1116 commented on src/components/model/Work/components/URLInput/hooks/index.ts
> +  const onInputKeyDown = (e: KeyboardEvent<HTMLInputElement>): void => {
![review:must](https://img.shields.io/badge/review-must-red.svg) 
handleChange関数とhandleSubmit関数に分けて下さい
handleChange関数ではInputに入力された文字列を変数に格納し、その文字列がurlとして正しいかどうかを見る関数
handleSubmit関数ではwarningが発生していないか、文字列が空でないかを見て空であるならそれ用のwarningに状態を切り替え、どちらもクリアしている場合はlinksに追加し現在のリンク入力欄をクリアして下さい
またhandleSubmitを使うためformタグを使って下さい
必要であればButtonも追加して下さい(参照:[discord](https://discord.com/channels/1033675089645948928/1164886041895895080/1188397284283658241))
example(あくまで例なので参考程度に)
```tsx
const handleChange = (e:ChangeEvent(HTMLInputElement))=>{
  setInput(e.target.value)
  // urlが正しいか、数が多くないかのチェック
 setWarning({})
}

const handleSubmit = (e:FormEvent<HTMLFormElement>)=>{
  if (input ===""){
    setWarning({})
   return
  }
 if   // urlが正しいか、数が多くないかのチェック

addLink(input)
setInput("")
}

<form onSubmit={handleSubmit}>
  <Input onChange={handleChange} value={input} />
  <Button>追加</Button>
</form>

```

2023-12-24 08:46 UTC, tosaken1116 commented on src/components/model/Work/components/URLInput/presentations/container.tsx
> +  useEffect(() => {
linksとlinkSetterをpropsでもらってuseUrlInput({links,linkSetter})ってやってuseUrlInput内で使うとuseEffectを使う必要がないので良きだと思われ！
ここなんでuseEffect使ったのか聞きたいです

2023-12-24 15:50 UTC, siloneco commented on src/components/model/Work/components/URLInput/presentations/container.tsx
> +  useEffect(() => {
なるほど、シンプルに値が変わったら関数実行したいなーと思いながら開発してたのでuseEffect使おうってなったんですが、確かにuseUrlInputに渡す方がスマートですね。直しておきました！

2023-12-24 16:12 UTC, tosaken1116 commented on src/components/model/Work/components/URLInput/index.test.tsx
> +    // Delete first url
テストケースは1機能1テストにしたいのでdelete linkのテストは別に設けた方がいいかも

2023-12-24 16:12 UTC, tosaken1116 commented on src/components/model/Work/components/URLInput/logics/index.test.ts
> +  it('returns false when its called with hostname without dot', () => {
クエリパラメータとかあっても問題ないかのテストもあるといいかも

2023-12-24 16:12 UTC, tosaken1116 commented on src/components/model/Work/components/URLInput/presentations/UrlListElement/index.tsx
> +  heightClassName: heightClassName,
このネームキャストはいらないかも

2023-12-24 16:12 UTC, tosaken1116 commented on src/components/model/Work/components/URLInput/presentations/main.tsx
> +    )}
https://github.com/Kyutech-C3/ToyBox_front_replace/assets/94045195/3b4b40c4-e98b-4aa6-85b2-e9c3a17f3299

ここレイアウトシフトが起きてるからstatusに関わらず縦幅持っておくといいかも

2023-12-24 16:12 UTC, tosaken1116 commented on src/components/model/Work/components/URLInput/presentations/main.tsx
> +          handleSubmit();
handleSubmitとpreventDefault切り離してるのgood

2023-12-26 05:53 UTC, tosaken1116 approved these changes
![LGTM](https://storage.googleapis.com/lgtm-ea733.appspot.com/lgtm/8249585)

2024-01-03 11:58 UTC, merged