作品に関するページの作成
Kyutech-C3/ToyBox_front_replace pull request #199
Opened 2024-04-05 12:14 UTC by tosaken1116

## issue番号

closes #6,#7,#17,#19,#20,#24,#25,#26,#27,#77,#79

## 変更点概要
投稿一覧画面
投稿詳細画面
投稿作成画面の作成

## 参考文献(あれば)

## スクリーンショット(必要であれば)

## チェック項目

- [x] テストが通ったか
- [x] ビルドが通ったか
- [x] `self assign`したか
- [x] レビュー優先度のラベルをつけたか

2024-04-08 14:26 UTC, K-Kizuku requested changes
ざっくりとは見た
レビュー漏れがあっても許してね

2024-04-08 14:26 UTC, K-Kizuku commented on src/components/functional/DropImage/hooks.ts
> +    console.log('in');
必要ないなら消したい

2024-04-08 14:26 UTC, K-Kizuku commented on src/components/functional/DropImage/hooks.ts
> +    console.log('in2');
必要ないなら消したい

2024-04-08 14:26 UTC, K-Kizuku commented on src/components/ui/DateDiffLabel/logic.ts
> +    return `${date.getMonth() + 1}/${date.getDate()}`;
月/日だけの表示だと，ユーザー視点今年のってわからんくない？
3ヶ月過ぎたらYYYY/MM/DDの表示に統一してもいい気が
(デザイン周りは既に話し合ってそうな気もするので，議論済みならスルーでOK)

2024-04-08 14:26 UTC, K-Kizuku commented on src/components/ui/MarkdownViewer/index.stories.tsx
> +};
storybook上での設定がないのは意図してる？

2024-04-08 14:26 UTC, K-Kizuku commented on src/domains/Work/components/WorkEdit/presentations/items/AssetUpload.tsx
> +        動画 [ .mp4 mov ]
ピリオドが抜けてる
```suggestion
        動画 [ .mp4 .mov ]
```

2024-04-08 14:26 UTC, K-Kizuku commented on src/domains/Work/components/WorkEdit/presentations/items/AssetUpload.tsx
> +        zip[ .zip]
後ろのスペースがない
```suggestion
        zip[ .zip ]
```

2024-04-08 14:26 UTC, K-Kizuku commented on src/constants/baseUrl/link.ts
> +export const TOYBOX_DESCRIPTION = 'https://toybox.c3js.org/';
URLの末尾に`/`があるのとないのがあるのは意図してる？
統一したくない？

2024-04-08 14:26 UTC, K-Kizuku commented on src/constants/baseUrl/baseUrl.ts
>      ? process.env['NEXT_PUBLIC_BACKEND_URL'] ?? 'http://localhost:4010'
他のところもだけどドット記法とブラケット記法が混ざってるのは何か理由あるの？

2024-04-08 14:26 UTC, K-Kizuku commented on src/domains/Work/components/WorkDetail/presentations/main.tsx
> +            <Typography>{url.url}</Typography>
このURLのリンクは飛べない仕様であってる？

2024-04-08 14:26 UTC, K-Kizuku commented on src/domains/Work/components/URLInput/presentations/main.tsx
<img width="333" alt="image" src="https://github.com/Kyutech-C3/ToyBox_front_replace/assets/83001474/eba06b7d-cebf-433d-8e43-1a99c6691bca">
バリデーションエラーは独自で実装しているはずなので，おそらくこれは意図していない挙動だと思われ
formに`novalidate`をつければ直りそう(未検証)

2024-04-08 14:54 UTC, tosaken1116 commented on src/constants/baseUrl/baseUrl.ts
>      ? process.env['NEXT_PUBLIC_BACKEND_URL'] ?? 'http://localhost:4010'
インデックスシグネチャの問題ですね(eslintに設定してある)


envには特定のkey以外はkeyとして存在しているかわからないのでブラケット記法を使うことでkeyをどんなものでも受け取れるようにする感じです


[[TypeScript]インデックスシグネチャで感覚的には理解できなかったことまとめ](https://qiita.com/sa_tech0518/items/59026af48a9aa24d383f)

2024-04-08 14:57 UTC, tosaken1116 commented on src/constants/baseUrl/link.ts
> +export const TOYBOX_DESCRIPTION = 'https://toybox.c3js.org/';
特に意図はないです〜
この辺に関してはまだmock dataなので本実装する時にトレーリングスラッシュ外して実装しておきます

2024-04-08 14:59 UTC, tosaken1116 commented on src/domains/Work/components/WorkDetail/presentations/main.tsx
> +            <Typography>{url.url}</Typography>
現行のtoyboxは飛べる仕様なので修正しておきます〜

2024-04-08 15:08 UTC, tosaken1116 commented on src/components/ui/DateDiffLabel/logic.ts
> +    return `${date.getMonth() + 1}/${date.getDate()}`;
デザイナーと相談しておきます〜

2024-04-09 12:38 UTC, K-Kizuku approved these changes
https://github.com/Kyutech-C3/ToyBox_front_replace/pull/199#discussion_r1555927759
これそのままでいいならOK

2024-04-09 12:49 UTC, merged