feat: add popover ui
Kyutech-C3/ToyBox_front_replace pull request #86
Opened 2023-11-08 16:12 UTC by siloneco

## issue番号

closes #80 

## 変更点概要
popoverのコンポーネントを作成しました

## 参考文献(あれば)
https://ui.shadcn.com/docs/components/popover

## スクリーンショット(必要であれば)
![image](https://github.com/Kyutech-C3/ToyBox_front_replace/assets/37594486/5c64624f-ddd2-4feb-9bb7-43ea9d87ed19)

## チェック項目

- [X] テストが通ったか
- [X] ビルドが通ったか
- [X] `self assign`したか
- [X] レビュー優先度のラベルをつけたか

2023-11-08 16:13 UTC, siloneco commented
Storybookが自動でargsを取得できないらしく、このようなエラー(?)が出ているのが気がかり  
対応は必要そうですか？
![image](https://github.com/Kyutech-C3/ToyBox_front_replace/assets/37594486/fce1d1f9-513a-4847-9f45-361b2320a400)

2023-11-08 16:28 UTC, tosaken1116 commented
> Storybookが自動でargsを取得できないらしく、このようなエラー(?)が出ているのが気がかり 対応は必要そうですか？ ![image](https://user-images.githubusercontent.com/37594486/281469628-fce1d1f9-513a-4847-9f45-361b2320a400.png)

これに関してはstorybookのargsはStoryオブジェクトのargsを参照しているためそこが指定されていない場合はそのような表示になります
renderに入れるラムダ関数は第一引数にargsを取ることができるため以下のように書くことでargsをインタラクティブに操作することができます(ローカル検証済み)

これの注意点としてはstoryに当て嵌めてるコンポーネント(ここではPopover)の引数の型情報が引き継がれないためユニオン型などに対応できないという点が挙げられます(ドキュメントなどを漁ればあるかもしれない)
ref:https://storybook.js.org/docs/react/writing-stories/introduction#:~:text=export%20const%20OneItem%3A%20Story%20%3D%20%7B%0A%20%20render%3A%20(args)%20%3D%3E%20(%0A%20%20%20%20%3CList%20%7B...args%7D%3E%0A%20%20%20%20%20%20%3CListItem%20/%3E%0A%20%20%20%20%3C/List%3E%0A%20%20)%2C

```ts
export const Default: Story = {
  args: {
    align: 'center',
    sideOffset: 96,
  },
  render: (args) => (
    <Popover>
      <PopoverTrigger>Popover</PopoverTrigger>
      <PopoverContent {...args}>Content</PopoverContent>
    </Popover>
  ),
};
```

2023-11-10 05:31 UTC, tosaken1116 requested changes

2023-11-10 05:31 UTC, tosaken1116 commented on src/components/ui/Popover/index.stories.tsx
> +};
Storiesに開いてる状態とalignによるコンテンツの位置の違いの状態が欲しいです
基本的にpropsにunion型がある場合は全パターンを列挙してもらえるとありがたいです

2023-11-10 05:31 UTC, tosaken1116 commented on src/components/ui/Popover/index.stories.tsx
> +};
それ以外は特に問題なさそうです

2023-11-10 05:45 UTC, K-Kizuku reviewed
一部気になるところがあったので合わせて修正お願いします

2023-11-10 05:45 UTC, K-Kizuku commented on src/components/ui/Popover/index.test.tsx
> +describe('ui/Popoverのテスト', () => {
ここのメッセージに関しては英語で統一するらしいです

2023-11-10 05:56 UTC, tosaken1116 requested changes

2023-11-10 05:56 UTC, tosaken1116 commented on src/components/ui/Popover/index.test.tsx
> +});
PopoverTriggerでアクションしたときにPopoverContentが表示されるのか、もう一度押したら非表示になるのかというテストが欲しいです

アクションに関してはuserEventというものがあるのでそれが使えると思います
参考にできそうなとこ:https://github.com/Kyutech-C3/ToyBox_front_replace/blob/develop/src/components/ui/Tooltip/index.test.tsx

2023-11-13 06:22 UTC, tosaken1116 approved these changes
![LGTM](https://storage.googleapis.com/lgtm-ea733.appspot.com/lgtm/8251349)

2023-11-13 10:08 UTC, merged